services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bold9-prod-graphql-server
    env_file: .env.prod
    ports:
      - "${EXPOSE_SERVER_PORT}:${EXPOSE_SERVER_PORT}"
    depends_on:
      - db
    networks:
      - bold9-net
    restart: always
  db:
    env_file: .env.prod